# Generated by Django 4.1.3 on 2022-12-20 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('wording', models.CharField(blank=True, max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=150, null=True)),
                ('updator', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('wording', models.CharField(blank=True, max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=150, null=True)),
                ('updator', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeeBySchool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('important', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=150, null=True)),
                ('updator', models.CharField(blank=True, max_length=150, null=True)),
                ('AcademicYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.academicyear')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
                ('SchoolFee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolfee')),
                ('SchoolFeeProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolfeeprofile')),
                ('SusGraduationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.susgraduationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionSchoolFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(blank=True, max_length=150, null=True)),
                ('updator', models.CharField(blank=True, max_length=150, null=True)),
                ('Inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.inscription')),
                ('SchoolFeeBySchool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schoolfeebyschool')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='SchoolFeeProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schoolfeeprofile'),
        ),
    ]
